# Brew
brew 'direnv'
brew 'git'
brew 'imagemagick'
brew 'node'
brew 'openssl'
brew 'postgresql'
brew 'pnpm'
brew 'python'
brew 'rbenv'
brew 'ssh-copy-id'
brew 'yarn'
brew 'zsh'

# Cask
cask '1password'
cask 'aldente'
cask 'anki'
cask 'dash'
cask 'discord'
cask 'figma'
cask 'firefox'
cask 'gitup'
cask 'iina'
cask 'insomnia'
cask 'mullvadvpn'
cask 'paw'
cask 'postgres'
cask 'spotify'
cask 'sublime-text'
cask 'transmission'
cask 'visual-studio-code'

# Optional cask apps
# cask 'fujifilm-x-raw-studio'
# cask 'omnidisksweeper'

# Fonts
tap 'homebrew/cask-fonts'
brew 'svn'

cask 'font-fira-mono'
cask 'font-jetbrains-mono'
cask 'font-noto-mono'
cask 'font-noto-sans'
cask 'font-noto-serif'
cask 'font-open-sans'
cask 'font-roboto-mono'
cask 'font-roboto'
